serializers task complete
TimofeiN/task_manager pull request #8
Opened 2023-04-27 14:30 UTC by TimofeiN

2023-04-28 07:49 UTC, aleksandr-semenov-dbp requested changes

2023-04-28 07:49 UTC, aleksandr-semenov-dbp commented on pyproject.toml
> +markdown = "^3.4.3"
А зачем этот модуль?

2023-04-28 14:03 UTC, TimofeiN commented on pyproject.toml
> +markdown = "^3.4.3"
Во введении к уроку было написано, понадобится markdown - вот я и установил)

2023-05-02 07:40 UTC, aleksandr-semenov-dbp approved these changes

2023-05-04 10:53 UTC, merged